<template>
  <b-row v-if="mode">
    <b-col class="centrify" v-for="key in keys" :key="key.letter">
      <base-drum-kit-key :sound="key"></base-drum-kit-key>
    </b-col>
  </b-row>
  <b-row v-else>
    <span v-for="key in keys" :key="key.letter">
      <drum-kit-timing :sound="key"></drum-kit-timing>
    </span>
  </b-row>
</template>

<script>
import BaseDrumKitKey from "@/components/BaseDrumKitKey.vue";
import DrumKitTiming from "./DrumKitTiming.vue";
export default {
  name: "DrumKitBody",
  props: ["mode"],
  components: {
    BaseDrumKitKey,
    DrumKitTiming,
  },
  data() {
    return {
      keys: [
        {
          name: "boom",
          audio: require("@/assets/drumkit/sounds/boom.wav"),
          letter: "A",
          timing: [
            false,
            false,
            false,
            false,
            false,
            false,
            false,
            false,
            false,
            false,
            false,
            false,
            false,
            false,
            false,
            false,
          ],
        },
        {
          name: "clap",
          audio: require("@/assets/drumkit/sounds/clap.wav"),
          letter: "S",
          timing: [
            false,
            false,
            false,
            false,
            false,
            false,
            false,
            false,
            false,
            false,
            false,
            false,
            false,
            false,
            false,
            false,
          ],
        },
        {
          name: "hihat",
          audio: require("@/assets/drumkit/sounds/hihat.wav"),
          letter: "D",
          timing: [
            false,
            false,
            false,
            false,
            false,
            false,
            false,
            false,
            false,
            false,
            false,
            false,
            false,
            false,
            false,
            false,
          ],
        },
        {
          name: "kick",
          audio: require("@/assets/drumkit/sounds/kick.wav"),
          letter: "F",
          timing: [
            false,
            false,
            false,
            false,
            false,
            false,
            false,
            false,
            false,
            false,
            false,
            false,
            false,
            false,
            false,
            false,
          ],
        },
        {
          name: "openhat",
          audio: require("@/assets/drumkit/sounds/openhat.wav"),
          letter: "G",
          timing: [
            false,
            false,
            false,
            false,
            false,
            false,
            false,
            false,
            false,
            false,
            false,
            false,
            false,
            false,
            false,
            false,
          ],
        },
        {
          name: "ride",
          audio: require("@/assets/drumkit/sounds/ride.wav"),
          letter: "Z",
          timing: [
            false,
            false,
            false,
            false,
            false,
            false,
            false,
            false,
            false,
            false,
            false,
            false,
            false,
            false,
            false,
            false,
          ],
        },
        {
          name: "snare",
          audio: require("@/assets/drumkit/sounds/snare.wav"),
          letter: "X",
          timing: [
            false,
            false,
            false,
            false,
            false,
            false,
            false,
            false,
            false,
            false,
            false,
            false,
            false,
            false,
            false,
            false,
          ],
        },
        {
          name: "tink",
          audio: require("@/assets/drumkit/sounds/tink.wav"),
          letter: "C",
          timing: [
            false,
            false,
            false,
            false,
            false,
            false,
            false,
            false,
            false,
            false,
            false,
            false,
            false,
            false,
            false,
            false,
          ],
        },
        {
          name: "tom",
          audio: require("@/assets/drumkit/sounds/tom.wav"),
          letter: "V",
          timing: [
            false,
            false,
            false,
            false,
            false,
            false,
            false,
            false,
            false,
            false,
            false,
            false,
            false,
            false,
            false,
            false,
          ],
        },
      ],
    };
  },
};
</script>

<style scoped></style>
